--- #PLAYBOOK FOR OS UPDATE USING YUM
- hosts: "{{ var_hosts }}"
  user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  roles:
    - { role: redhat_os_upgrade,    when: "ansible_distribution_major_version != '5'" }
    - { role: redhat_os_upgrade_rhel5,    when: "ansible_distribution_major_version == '5'" }
