--- #PLAYBOOK FOR OS UPDATE USING APT
- hosts: "{{ var_hosts }}"
  user: "{{ var_remote_user }}"
  sudo: "{{ var_sudo }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  roles:
    - ubuntu_os_upgrade
